parameters:
#    harvest_cloud_stripe.example.class: HarvestCloud\StripeBundle\Example

services:
#    harvest_cloud_stripe.example:
#        class: %harvest_cloud_stripe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
