parameters:
    harvest_cloud_stripe.stripe.class: HarvestCloud\StripeBundle\Stripe

services:
#    harvest_cloud_stripe.example:
#        class: %harvest_cloud_stripe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    payment.stripe:
        class: %harvest_cloud_stripe.stripe.class%
        arguments:
          - %payment.stripe.secret_key%
          - %payment.stripe.publishable_key%
